export enum ErrorCode {
  PHONE_NOT_FOUND = 'PHONE_NOT_FOUND',
  PHONE_DETAILS_FAILED = 'PHONE_DETAILS_FAILED',
  PHONE_LIST_FAILED = 'PHONE_LIST_FAILED',
  PHONE_SEARCH_FAILED = 'PHONE_SEARCH_FAILED',
  CART_ADD_FAILED = 'CART_ADD_FAILED',
  CART_REMOVE_FAILED = 'CART_REMOVE_FAILED',
  CART_LOAD_FAILED = 'CART_LOAD_FAILED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  DEFAULT = 'DEFAULT',
}
